repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: \.md$
      - id: trailing-whitespace
      - id: check-toml
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.4.3
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.4.1
    hooks:
      - id: tox-ini-fmt
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.3
    hooks:
      - id: actionlint
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.19.1"
    hooks:
      - id: blacken-docs
        files: pathlibutil/
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
  - repo: https://github.com/google/yamlfmt
    rev: v0.13.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--max-line-length", "88", "--exclude=examples/**"]
  - repo: https://github.com/d-chris/jinja2_pdoc
    rev: v1.1.1
    hooks:
      - id: jinja2pdoc
        files: docs/README\.md\.jinja2$
