[tox]
requires =
    tox>=4.2
env_list =
    py314
    py313
    py312
    py311
    py311-7z
    py310
    py39
    py38
no_package = true

[testenv]
skip_install = true
set_env =
    COVERAGE_FILE = {env_dir}/.coverage
commands_pre =
    poetry install --sync --no-interaction --only main,test
commands =
    poetry run pytest -v
allowlist_externals =
    poetry

[testenv:py311-7z]
commands_pre =
    poetry install --sync --no-interaction --only main,test --extras 7z
